WIP Update dev procedure for libsnowflakeclient
snowflakedb/libsnowflakeclient pull request #275
Opened 2021-03-10 22:24 UTC by sfc-gh-zli

2021-03-10 23:17 UTC, sfc-gh-kbhatia commented on ci/dev/README.rst
> +        export BUILD_TYPE='Debug' # or 'Release' for release build
Why this change ?

2021-03-10 23:18 UTC, sfc-gh-kbhatia commented on ci/dev/README.rst
> +        export BUILD_TYPE='Debug' # or 'Release' for release build
Never mind, I realized that this is in the docs.

2021-03-24 07:14 UTC, sfc-gh-vreddy requested changes
Secretdetector changes are must for ODBC and other client drivers.
This should NOT be merged.

2021-03-24 16:32 UTC, sfc-gh-zli commented
Yes I agree. I used this branch to build the current .a file for XP and I don't intend to merge it. Let me close this PR.

2021-03-24 16:32 UTC, closed without merging

2021-03-24 16:33 UTC, sfc-gh-zli commented
But please don't delete this branch yet. This might be useful before we update our workflow of checking in the .a file.