SNOW-715510: MFA Token cache for libsnowflakeclient
snowflakedb/libsnowflakeclient pull request #773
Opened 2024-11-07 19:00 UTC by sfc-gh-jszczerbinski

2024-11-14 13:04 UTC, sfc-gh-mkubik commented on cpp/platform/SecureStorageImpl.hpp
> +     * API to secure store credential in Apple Keychain
or Windows Credential Manager?

2024-11-14 13:06 UTC, sfc-gh-mkubik commented on cpp/platform/SecureStorageApple.cpp
> +#define DRIVER_NAME "SNOWFLAKE_ODBC_DRIVER"
Same concern as above

2024-11-15 10:49 UTC, sfc-gh-astachowski commented on cpp/platform/SecureStorageWin.cpp
> +    return storeToken(host, username, credType, token);
Nit: this will cause a slightly misleading log

2024-11-15 10:49 UTC, sfc-gh-astachowski commented on cpp/platform/SecureStorageWin.cpp
> +    }
I think we should have some logs here

2024-11-15 10:49 UTC, sfc-gh-astachowski commented on cpp/platform/SecureStorageApple.cpp
> +
I'd add a debug log informing about success to match the other functions

2024-11-15 10:49 UTC, sfc-gh-astachowski commented on tests/mock/test_mock_mfa_token_caching.c
> +    free(first_mfa_request);
Why free only the first request?

2024-11-19 14:49 UTC, sfc-gh-jszczerbinski commented on cpp/lib/CacheFile.cpp
> +    return false;
File caches are not used on windows at all. This definition ensures that the code compiles on windows, but in practice it's never used.

2024-11-19 15:04 UTC, sfc-gh-jszczerbinski commented on cpp/lib/CacheFile.cpp
> +    auto accountCacheIt = pair.first;
1. picojson::object in pratice is an alias for std::map<std::string, picojson::value>
```cpp
    typedef std::map<std::string, value> object;
```
2. Doc of the emplace method https://en.cppreference.com/w/cpp/container/map/emplace
3. This code would be clear with more modern c++
```cpp
/* inserted is true if key.account wasn't in obj and we added new element */
 auto [accountCacheIt, inserted] pair = obj.emplace(key.account, picojson::value(picojson::object())); 
```

2024-11-19 15:06 UTC, sfc-gh-jszczerbinski commented on cpp/lib/CredentialCache.cpp
> +        CXX_LOG_ERROR("Failed to get token. Could not acquire file lock(path=%s)", lock.getPath().c_str());
Probably not, but I tried not to change original implementation due to BCR concerns

2024-11-19 15:27 UTC, sfc-gh-jszczerbinski commented on cpp/platform/SecureStorageApple.cpp
> +    OSStatus result = errSecSuccess;
This old c-style. Historically most c compilers required all variable declarations to be at the start of the function. Moving declaration to the place of use.

2024-11-19 15:27 UTC, sfc-gh-jszczerbinski commented on cpp/lib/CacheFile.cpp
> +      "TMP"
I agree, but removing it is a BCR in ODBC.

2024-11-19 15:29 UTC, sfc-gh-jszczerbinski commented on cpp/lib/CacheFile.cpp
> +//
Sure. CLion generated it and I forgot to delete it.

2024-11-19 15:33 UTC, sfc-gh-jszczerbinski commented on cpp/lib/CacheFile.cpp
> +      "TMP"
I will make changes after security modeling is complete

2024-11-19 15:43 UTC, sfc-gh-dprzybysz commented on cpp/lib/CacheFile.cpp
> +    return false;
maybe then just make the code unnacessible from the beginning? For MacOS are we using the file cache or some secure storage?

2025-01-14 14:46 UTC, sfc-gh-jszczerbinski commented on cpp/lib/CacheFile.cpp
> +    if (!ensurePermissions(path, 0700))
600 good catch

2025-01-14 16:11 UTC, sfc-gh-jszczerbinski commented on cpp/lib/CacheFile.cpp
> +    return false;
We could, but we would like to keep the code as platform agnostic as possible. Compiling it ensures that even if we don't want to run it.

On MacOs we use secure storage.

2025-01-28 10:54 UTC, sfc-gh-jszczerbinski commented on tests/test_manual_connect.c
> +    snowflake_set_attribute(sf, SF_CON_APPLICATION_NAME, "ODBC");
For now, I already enabled for libsnowflakeclient on backend: https://github.com/snowflakedb/snowflake/pull/245837

2025-01-28 16:20 UTC, sfc-gh-mhofman requested changes

2025-01-28 16:20 UTC, sfc-gh-mhofman commented on include/snowflake/CredentialCache.hpp
> +      case CredentialType::MFA_TOKEN:
what about SSO token?

2025-02-03 10:05 UTC, sfc-gh-mmishchenko reviewed
Looks headers aren't ordered consistently across the changes

2025-02-03 10:11 UTC, sfc-gh-jszczerbinski commented on include/snowflake/CredentialCache.hpp
> +      case CredentialType::MFA_TOKEN:
Added

2025-02-03 10:11 UTC, sfc-gh-jszczerbinski commented on cpp/platform/FileLock.cpp
> +    if (creation_time_epoch_seconds + 60 < now_epoch_seconds)
Done

2025-02-03 13:59 UTC, sfc-gh-dprzybysz reviewed
I endded review before cpp/util/Sha256.cpp, tomorrow I will continue

2025-02-03 13:59 UTC, sfc-gh-dprzybysz commented on cpp/platform/FileLock.hpp
> + * File:   FileLock.hpp *
I think we could skip file name in header in all places

2025-02-03 13:59 UTC, sfc-gh-dprzybysz commented on cpp/platform/SecureStorageApple.cpp
> +    CXX_LOG_DEBUG("Successfully removed secure token");
should be in else for the if above?

2025-02-03 14:28 UTC, sfc-gh-jszczerbinski commented on cpp/platform/FileLock.hpp
> + * File:   FileLock.hpp *
We should probably skip the copyright notices altogether?

2025-02-03 14:30 UTC, sfc-gh-jszczerbinski commented on cpp/platform/SecureStorageApple.cpp
> +    CXX_LOG_DEBUG("Successfully removed secure token");
Good catch, but I used switch case instead.

2025-02-03 17:44 UTC, sfc-gh-mhofman requested changes

2025-02-03 17:44 UTC, sfc-gh-mhofman commented on include/snowflake/SecureStorage.hpp
> + * Copyright (c) 2013-2020 Snowflake Computing
2013-2025

2025-02-03 17:44 UTC, sfc-gh-mhofman commented on include/snowflake/secure_storage.h
> + * File:   mfa_token_cache.h *
wrong file name

2025-02-03 17:44 UTC, sfc-gh-mhofman commented on lib/client.c
> +    // TODO Enable token cache
this still to be left commented out? If yes let's have a tracking jira number here

2025-02-03 17:44 UTC, sfc-gh-mhofman commented on lib/client.c
> +/*
as above - tracking jira

2025-02-04 06:33 UTC, sfc-gh-dprzybysz commented on cpp/platform/FileLock.hpp
> + * File:   FileLock.hpp *
I agree but let's do the cleanup in a separate PRs in all drivers

2025-02-04 10:01 UTC, sfc-gh-jszczerbinski commented on include/snowflake/SecureStorage.hpp
> + * Copyright (c) 2013-2020 Snowflake Computing
I resolved it, because we discussed it offline

2025-02-04 11:05 UTC, sfc-gh-jszczerbinski commented on include/snowflake/secure_storage.h
> +secure_storage_ptr secure_storage_init();
This is minimal necessary api

2025-02-04 11:10 UTC, sfc-gh-jszczerbinski commented on include/snowflake/SecureStorage.hpp
> +namespace Client {
Most of the files in this directory are for pdo_snowflake and ODBC

2025-02-04 11:15 UTC, sfc-gh-dprzybysz commented on include/snowflake/SecureStorage.hpp
> +namespace Client {
we should definitely be explicit and describe which files and functions we expose as our public API of libsnowflakeclient and what is necessary only for the internal products

2025-02-04 11:19 UTC, sfc-gh-jszczerbinski commented on tests/test_unit_secure_storage.cpp
> +  assert_true(ss.retrieveToken(key1, retrievedToken) == SecureStorageStatus::NotFound);
We do not, but it should be still not found. I could imagine a scenario where first delete was performed incorrectly, but second delete mad key1 credential available again.

2025-02-04 11:26 UTC, sfc-gh-jszczerbinski commented on tests/test_unit_secure_storage.cpp
> +  assert_true(ss.storeToken(key1, token1) == SecureStorageStatus::Success);
There is asset_int_equals, but it has no advantages in terms of error codes and this is more readable to me.

2025-02-04 14:41 UTC, sfc-gh-mhofman approved these changes

2025-02-05 06:33 UTC, sfc-gh-dprzybysz commented on include/snowflake/SecureStorage.hpp
> +namespace Client {
discussed offline that we should do it in a separate issue

2025-02-05 06:34 UTC, sfc-gh-dprzybysz approved these changes

2025-02-05 09:01 UTC, merged